[PP-8] Limpeza e transformação de dados
andyboli/puc-projeto pull request #8
Opened 2022-11-14 22:11 UTC by andyboli

# Context

[Jira](https://puc-projeto.atlassian.net/jira/software/projects/PP/boards/2?selectedIssue=PP-8)

2022-11-16 23:07 UTC, Helphs requested changes
A coluna birthday deveria ser tipo data.

2022-11-16 23:07 UTC, Helphs commented on controller/reader.py
> -def map_field(field):
Precisa fazer o tratamento para corrigir a palavra 'não' que desconfigurou

2022-11-16 23:07 UTC, Helphs commented on controller/reader.py
> -def map_age_bracket(age_bracket):
Range de idade para fazermos o agrumapento no painel

2022-11-28 22:53 UTC, andyboli commented on controller/reader.py
> -def map_age_bracket(age_bracket):
O range de idade vai ser utilizado em outro momento, aqui estamos fazendo o map para salvar os dados no banco, o range de idade vai ser usado na hora de fazermos a exibição do dado nos gráficos

2022-11-28 22:53 UTC, andyboli commented on controller/reader.py
> -def map_field(field):
Boa, para conseguir megear essa logo vou olhar isso na PR que to trabalhando agora

2022-11-28 22:53 UTC, merged